name: 'Build and Deploy'
on:
  push:
    branches:
      - dev
  schedule:
    # rebuild and deploy every hour at 54th min to help with the latest post and expired signed image links from notion
    - cron: '54 * * * *'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Checkout # check out the source code of repo branch dev into runner then run command against the source code below
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Build
        env:
          REVIEWS_PAGE_ID: ${{ secrets.REVIEWS_PAGE_ID }}
          MISC_PAGE_ID: ${{ secrets.MISC_PAGE_ID }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        run: |
          npm ci
          npm run build
          touch build/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN_GITHUB }}
          BRANCH: dev-preview
          FOLDER: build
          CLEAN: true
