name: 'Build and Deploy'
on:
  push:
    branches:
      - dev

env:
  REVIEWS_PAGE_ID: ${{ secrets.REVIEWS_PAGE_ID }}
  NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout # check out the source code of repo branch dev into runner then run command against the source code below
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Build
        run: |
          npm ci
          npm run build
          touch build/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN_GITHUB }}
          BRANCH: dev-preview
          FOLDER: build
          CLEAN: true
