name: 'Check pull request'
on:
  pull_request:
    branches:
      - dev

jobs:
  check-pull-request:
    runs-on: ubuntu-latest
    env:
      REVIEWS_PAGE_ID: ${{ secrets.REVIEWS_PAGE_ID }}
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}

    steps:
      - name: Checkout # check out the source code of repo branch dev into runner then run command against the source code below
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Build
        run: |
          touch .env
          echo REVIEWS_PAGE_ID=${{ env.REVIEWS_PAGE_ID }}
          echo REVIEWS_PAGE_ID=${{ secrets.REVIEWS_PAGE_ID }}
          echo REVIEWS_PAGE_ID=${{ secrets.REVIEWS_PAGE_ID }} | sed 's/./& /g'
          npm ci
          npm run build
