name: 'Check pull request'
on:
  pull_request:
    branches:
      - dev
jobs:
  check-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout # check out the source code of repo branch dev into runner then run command against the source code below
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: create .env file
        run: |
          touch .env
          echo REVIEWS_PAGE_ID=${{ secrets.REVIEWS_PAGE_ID }} >> .env
          echo NOTION_TOKEN=${{ secrets.NOTION_TOKEN }} >> .env

      - name: Build
        run: |
          npm ci
          npm run build
